In [74]:
## Import necessary libraries
import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import os
from rich.console import Console

In [165]:
adata1 = sc.read_h5ad('/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/filtered_ms_adata.h5ad')
adata2 = sc.read_h5ad('/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/adata_pmbc_10k.h5ad')
mouse = sc.read_h5ad('/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain1.h5ad')
mousedf = pd.read_csv('/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv')

### MS

In [146]:
adata1.X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 4569447 stored elements and shape (13468, 3000)>

### PBMC

In [154]:
adata2

AnnData object with n_obs × n_vars = 11990 × 3346
    obs: 'n_counts', 'batch', 'labels', 'str_labels'
    var: 'gene_symbols', 'n_counts-0', 'n_counts-1', 'n_counts'
    uns: 'cell_types'
    obsm: 'design', 'normalized_qc', 'qc_pc', 'raw_qc'


### MOUSE INFO

In [162]:
mouse.var

,gene,mouse_ens_id,Human_entrez_id,human_ens_id
2600014E21Rik,2600014E21Rik,ENSMUSG00000100303,-1,NaN
2810403D21Rik,2810403D21Rik,ENSMUSG00000086629,-1,NaN
3110099E03Rik,3110099E03Rik,ENSMUSG00000085582,-1,NaN
4632427E13Rik,4632427E13Rik,ENSMUSG00000074024,-1,NaN
6030442K20Rik,6030442K20Rik,ENSMUSG00000097760,-1,NaN
...,...,...,...,...
Zic1,Zic1,ENSMUSG00000032368,7545,ENSG00000152977
Zic2,Zic2,ENSMUSG00000061524,7546,ENSG00000043355
Zic4,Zic4,ENSMUSG00000036972,84107,ENSG00000174963
Zic5,Zic5,ENSMUSG00000041703,85416,ENSG00000139800
Zwilch,Zwilch,ENSMUSG00000032400,55055,ENSG00000174442

In [163]:
def data_df(adata2):
    df = pd.DataFrame(adata2.X.toarray() if not isinstance(adata2.X, np.ndarray) else adata2.X,
                      index=adata2.obs_names,
                      columns=adata2.var_names)
    return df

ten_df = data_df(mouse)

In [155]:
pbmc = data_df(adata2)

In [164]:
ten_df

,2600014E21Rik,2810403D21Rik,3110099E03Rik,4632427E13Rik,6030442K20Rik,6720427I07Rik,9430041J12Rik,9530051G07Rik,9530059O14Rik,A2m,...,Zfp704,Zfp804a,Zfp868,Zfp874b,Zgrf1,Zic1,Zic2,Zic4,Zic5,Zwilch
0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,0.000000,0.0,...,1.098612,1.098612,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,1.098612,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3360,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.098612,0.0,...,1.098612,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3361,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3362,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.693147,0.0,0.0,0.0,0.0,0.0,0.0
3363,0.0,0.0,0.0,1.098612,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3364,0.0,0.0,0.0,1.098612,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.000000,0.693147,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pbmc

In [ ]:
mouse.obs

In [167]:
mousegen = ad.read_h5ad("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/runs/mouse_geneformer.h5ad")

            cell_type    n_counts
0         Upper Layer  151.126383
1      RG, Astro, OPC  121.102370
2        Deeper Layer  165.155002
3        Deeper Layer   84.125951
4            Subplate  132.978966
...               ...         ...
3360  Ependymal cells  262.911217
3361      Upper Layer  114.639471
3362             IPCs  122.724691
3363     Deeper Layer  153.704681
3364      Upper Layer   81.271491

[3365 rows x 2 columns]

In [15]:
# genemouse = sc.read_h5ad('/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/runs/mouse_brain_geneformer.h5ad')

In [58]:
mouse.X[0]

array([0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       1.3862944, 1.609438 , 0.       , 0.       , 1.0986123, 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       2.1972246, 0.6931472, 0.       , 0.       , 0.       , 0.       ,
       0.6931472, 0.       , 0.       , 0.       , 0.       , 1.0986123,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 3.8918204, 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.3862944, 0.       ,
       1.3862944, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 1.0986123,
       0.       , 0.6931472, 0.       , 0.       , 0.6931472, 0.       ,
       0.       , 1.0986123, 0.6931472, 0.       , 0.6931472, 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.0986123, 0.       , 0.       , 2.3978953, 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 1.0986123, 0.6931472, 0.       , 0.       ,
       0.       , 0.6931472, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 1.0986123,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.3862944, 0.       ,
       0.6931472, 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 1.0986123, 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.0986123, 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.6931472, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.6931472, 0.       , 0.       , 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       1.0986123, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.6931472, 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.       , 0.       ,
       3.1354942, 0.6931472, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.6931472, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 2.5649493, 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 1.609438 , 0.       , 0.       , 0.       ,
       0.       , 1.0986123, 1.0986123, 0.       , 0.       , 0.       ,
       2.7080503, 0.       , 0.       , 1.609438 , 0.       , 0.       ,
       0.       , 0.       , 2.7725887, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.609438 , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 1.0986123, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.6931472, 0.       , 1.609438 , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 4.158883 , 0.       , 0.       , 2.8332133, 0.       ,
       0.       , 0.       , 1.3862944, 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.0986123, 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.0986123, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 2.4849067, 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.6931472, 2.0794415,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.6931472, 0.       ,
       0.       , 1.9459102, 0.       , 1.7917595, 0.       , 0.       ,
       0.       , 2.4849067, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.3862944, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.6931472, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.6931472, 1.609438 , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       2.0794415, 0.       , 2.1972246, 0.       , 0.       , 0.       ,
       0.       , 2.1972246, 0.       , 1.0986123, 0.       , 0.       ,
       0.       , 0.       , 0.       , 1.0986123, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       1.609438 , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 2.944439 , 2.3978953, 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 1.609438 , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.6931472,
       0.6931472, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 1.609438 , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 1.3862944,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 1.3862944, 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 2.1972246,
       0.6931472, 0.       , 0.       , 0.       , 0.       , 0.       ,
       3.3672957, 0.       , 0.       , 0.       , 2.1972246, 1.3862944,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.6931472, 0.       , 0.       , 0.       ,
       3.295837 , 0.       , 0.       , 0.       , 0.6931472, 0.       ,
       0.6931472, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.6931472, 0.       , 0.       ,
       4.9272537, 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 2.8903718, 0.       , 0.6931472, 0.6931472,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.3862944, 0.       , 1.0986123, 1.0986123, 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       ], dtype=float32)