In [189]:
## Import necessary libraries
import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import os
from rich.console import Console

con = Console()

In [247]:
# load in the data using scanpy
adata = ad.read_h5ad("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/filtered_ms_adata.h5ad")
mouse_data = ad.read_h5ad("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/runs/mouse_geneformer.h5ad")

The mouse brain data

In [4]:
con = Console()

In [304]:
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv")
con.print("DataFrame loaded successfully.", style="bold green")

DataFrame loaded successfully.

In [308]:
df

,Unnamed: 0,cell_type,2600014E21Rik,2810403D21Rik,3110099E03Rik,4632427E13Rik,6030442K20Rik,6720427I07Rik,9430041J12Rik,9530051G07Rik,...,Zfp704,Zfp804a,Zfp868,Zfp874b,Zgrf1,Zic1,Zic2,Zic4,Zic5,Zwilch
0,AAACAGCCAACCGCCA-1,Upper Layer,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,1.098612,1.098612,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,AAACAGCCAAGGTCGA-1,"RG, Astro, OPC",0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,AAACAGCCAGGAACAT-1,Deeper Layer,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,AAACAGCCATATTGAC-1,Deeper Layer,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,AAACAGCCATGGTTAT-1,Subplate,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,1.098612,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3360,TTTGTGGCATAATCGT-1,Ependymal cells,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,1.098612,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3361,TTTGTGGCATTTGCTC-1,Upper Layer,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3362,TTTGTGTTCAATGACC-1,IPCs,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.693147,0.0,0.0,0.0,0.0,0.0,0.0
3363,TTTGTTGGTGGAGCAA-1,Deeper Layer,0.0,0.0,0.0,1.098612,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3364,TTTGTTGGTTAGAGCC-1,Upper Layer,0.0,0.0,0.0,1.098612,0.0,0.0,0.0,0.0,...,0.000000,0.693147,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [136]:
df["Unnamed: 0"]

0       AAACAGCCAACCGCCA-1
1       AAACAGCCAAGGTCGA-1
2       AAACAGCCAGGAACAT-1
3       AAACAGCCATATTGAC-1
4       AAACAGCCATGGTTAT-1
               ...
3360    TTTGTGGCATAATCGT-1
3361    TTTGTGGCATTTGCTC-1
3362    TTTGTGTTCAATGACC-1
3363    TTTGTTGGTGGAGCAA-1
3364    TTTGTTGGTTAGAGCC-1
Name: Unnamed: 0, Length: 3365, dtype: object

In [128]:
df.index = df.index.astype(str)
con.print("Index converted to string successfully.", style="bold green")

Index converted to string successfully.

In [130]:
df["Unnamed: 0"]

0       AAACAGCCAACCGCCA-1
1       AAACAGCCAAGGTCGA-1
2       AAACAGCCAGGAACAT-1
3       AAACAGCCATATTGAC-1
4       AAACAGCCATGGTTAT-1
               ...
3360    TTTGTGGCATAATCGT-1
3361    TTTGTGGCATTTGCTC-1
3362    TTTGTGTTCAATGACC-1
3363    TTTGTTGGTGGAGCAA-1
3364    TTTGTTGGTTAGAGCC-1
Name: Unnamed: 0, Length: 3365, dtype: object

In [125]:
# turn the objects into a string 
df["Unnamed: 0"] = df["Unnamed: 0"].astype(str)
df["cell_type"] = df["cell_type"].astype(str)

#Transpose the data 
df = df.T
df.iloc[2:, 0:] = df.iloc[2:, 0:].astype(float)

In [83]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364
Unnamed: 0,AAACAGCCAACCGCCA-1,AAACAGCCAAGGTCGA-1,AAACAGCCAGGAACAT-1,AAACAGCCATATTGAC-1,AAACAGCCATGGTTAT-1,AAACATGCACTTACAG-1,AAACCAACAACTGGGA-1,AAACCGCGTCACCAAA-1,AAACCGCGTGCAATGC-1,AAACCGGCAACTAACT-1,...,TTTGTCTAGAATCTCA-1,TTTGTCTAGTCCTTCA-1,TTTGTCTAGTTGCCTC-1,TTTGTGAAGCTGGAAA-1,TTTGTGGCACTCAACA-1,TTTGTGGCATAATCGT-1,TTTGTGGCATTTGCTC-1,TTTGTGTTCAATGACC-1,TTTGTTGGTGGAGCAA-1,TTTGTTGGTTAGAGCC-1
cell_type,Upper Layer,"RG, Astro, OPC",Deeper Layer,Deeper Layer,Subplate,Upper Layer,"RG, Astro, OPC","RG, Astro, OPC",Upper Layer,Upper Layer,...,Upper Layer,Ependymal cells,Upper Layer,Upper Layer,IPCs,Ependymal cells,Upper Layer,IPCs,Deeper Layer,Upper Layer
2600014E21Rik,0.0,0.0,0.0,0.0,0.0,0.693147,0.693147,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2810403D21Rik,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3110099E03Rik,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [150]:
type(df.iloc[:,0].to_frame())

pandas.core.frame.DataFrame

In [172]:
frame_values = df.iloc[:,1:]
frame_values_values = frame_values.values.astype(np.float32)

In [174]:
adata = ad.AnnData(X=frame_values_values)
adata.obs = df.iloc[:,0].to_frame()
con.print("AnnData object created successfully.", style="bold green")

AnnData object created successfully.

In [188]:
adata

AnnData object with n_obs × n_vars = 3365 × 865
    obs: 'cell_type'

In [159]:
adata.write("mouse_brain.h5ad")

Try again

In [ ]:
# Load your CSV
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv", index_col=0)
df["cell_type"] = df["cell_type"].astype(str)

In [231]:
frame = df.iloc[:, 1:].T.astype(np.float32).T.values
frame

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(3365, 865), dtype=float32)

In [228]:
celltype = df.iloc[:,0].to_frame()
celltype

                          cell_type
AAACAGCCAACCGCCA-1      Upper Layer
AAACAGCCAAGGTCGA-1   RG, Astro, OPC
AAACAGCCAGGAACAT-1     Deeper Layer
AAACAGCCATATTGAC-1     Deeper Layer
AAACAGCCATGGTTAT-1         Subplate
...                             ...
TTTGTGGCATAATCGT-1  Ependymal cells
TTTGTGGCATTTGCTC-1      Upper Layer
TTTGTGTTCAATGACC-1             IPCs
TTTGTTGGTGGAGCAA-1     Deeper Layer
TTTGTTGGTTAGAGCC-1      Upper Layer

[3365 rows x 1 columns]

In [239]:
adata = ad.AnnData(X=frame)
adata.obs = celltype
adata.obs_names = df.index.astype(str)
adata.var_names = df.columns[1:].astype(str)

In [243]:
adata.var_names

Index(['2600014E21Rik', '2810403D21Rik', '3110099E03Rik', '4632427E13Rik',
       '6030442K20Rik', '6720427I07Rik', '9430041J12Rik', '9530051G07Rik',
       '9530059O14Rik', 'A2m',
       ...
       'Zfp704', 'Zfp804a', 'Zfp868', 'Zfp874b', 'Zgrf1', 'Zic1', 'Zic2',
       'Zic4', 'Zic5', 'Zwilch'],
      dtype='object', length=865)

In [244]:
output_dir = "/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/"
filename = "mouse_brain.h5ad"
filepath = os.path.join(output_dir, filename)
os.makedirs(output_dir, exist_ok=True)

adata.write_h5ad(filepath)
con.print(f"AnnData object saved to {filepath}", style="bold green")

AnnData object saved to /Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain.h5ad

### Third TRY

In [438]:
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv")  # already loaded in your case

In [ ]:
df.drop(columns=['BC005561', 'C430049B03Rik', 'D1Ertd622e', 'Gm10125', 'H2afz', 'Qk', 'Sept4'], inplace=True)

In [440]:
from mygene import MyGeneInfo
mg = MyGeneInfo()

In [453]:
var_list = df.columns[2:].tolist()
mouse_list = mg.querymany(var_list, scopes='symbol', fields='ensembl.gene', species='mouse')

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
14 input query terms found dup hits:	[('2600014E21Rik', 2), ('4632427E13Rik', 2), ('6720427I07Rik', 2), ('A330093E20Rik', 2), ('C030005K0

In [454]:
dicts = {}
for r in mouse_list:
    word = r.get('ensembl', {}).get('gene') if isinstance(r.get('ensembl'), dict) else None
    if word is not None:
        dicts[r["query"]] = word

In [459]:
mouse_gene = var["ENS_id"].to_list()

In [547]:
obs = df[["cell_type"]]   
var = df.columns.to_frame().iloc[2:, :].astype(str) 
var = var.rename(columns={0: "gene"})
var["mouse_ens_id"] = var["gene"].map(dicts)
var["Human_entrez_id"] = var["mouse_ens_id"].map(mouse_to_human_dicts).fillna(-1).astype(int).astype(str)
var["human_ens_id"] = var["Human_entrez_id"].map(human_gene_mapper).replace(-1, "NaN")
X = df.drop(columns=["cell_type", "Unnamed: 0"])

In [555]:
var

,gene,mouse_ens_id,Human_entrez_id,human_ens_id
2600014E21Rik,2600014E21Rik,ENSMUSG00000100303,-1,NaN
2810403D21Rik,2810403D21Rik,ENSMUSG00000086629,-1,NaN
3110099E03Rik,3110099E03Rik,ENSMUSG00000085582,-1,NaN
4632427E13Rik,4632427E13Rik,ENSMUSG00000074024,-1,NaN
6030442K20Rik,6030442K20Rik,ENSMUSG00000097760,-1,NaN
...,...,...,...,...
Zic1,Zic1,ENSMUSG00000032368,7545,ENSG00000152977
Zic2,Zic2,ENSMUSG00000061524,7546,ENSG00000043355
Zic4,Zic4,ENSMUSG00000036972,84107,ENSG00000174963
Zic5,Zic5,ENSMUSG00000041703,85416,ENSG00000139800
Zwilch,Zwilch,ENSMUSG00000032400,55055,ENSG00000174442

In [556]:
adata = ad.AnnData(X=X, obs=obs, var=var)

/Users/macbook/Desktop/EECS545/545finalproject/.conda/lib/python3.11/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [557]:
adata

AnnData object with n_obs × n_vars = 3365 × 858
    obs: 'cell_type'
    var: 'gene', 'mouse_ens_id', 'Human_entrez_id', 'human_ens_id'

In [558]:
output_dir = "/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/"
filename = "mouse_brain1.h5ad"
filepath = os.path.join(output_dir, filename)
os.makedirs(output_dir, exist_ok=True)

adata.write_h5ad(filepath)
con.print(f"AnnData object saved to {filepath}", style="bold green")

AnnData object saved to
/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain1.h5ad

In [ ]:
human_orthologs = mg.querymany(mouse_gene, scopes='ensembl.gene', fields='homologene', species='mouse')

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
2 input query terms found no hit:	['nan', 'nan']

In [476]:
def find_human_entrez_id(homologene_genes_list):
    for species_id, gene_id in homologene_genes_list:
        if species_id == 9606:
            return gene_id
    return None

In [477]:
mouse_to_human_dicts = {}
for r in human_orthologs:
    word = r.get('homologene', {}) if isinstance(r.get('homologene'), dict) else None
    if word is not None:
        mouse_to_human_dicts[r["query"]] = find_human_entrez_id(word["genes"])

In [495]:
mouse_to_human_dicts

{'ENSMUSG00000030111': 2,
 'ENSMUSG00000015243': 19,
 'ENSMUSG00000041828': None,
 'ENSMUSG00000032849': 10257,
 'ENSMUSG00000030249': 10060,
 'ENSMUSG00000055782': 225,
 'ENSMUSG00000044337': 57007,
 'ENSMUSG00000022893': 9510,
 'ENSMUSG00000053399': 170692,
 'ENSMUSG00000053441': 171019,
 'ENSMUSG00000022894': 11096,
 'ENSMUSG00000046169': 11174,
 'ENSMUSG00000030022': 56999,
 'ENSMUSG00000052551': 105,
 'ENSMUSG00000020431': 107,
 'ENSMUSG00000024256': 116,
 'ENSMUSG00000025475': 84435,
 'ENSMUSG00000033569': 577,
 'ENSMUSG00000028184': 23266,
 'ENSMUSG00000037605': 23284,
 'ENSMUSG00000069170': 84059,
 'ENSMUSG00000025083': 84632,
 'ENSMUSG00000019986': 54806,
 'ENSMUSG00000039546': 55966,
 'ENSMUSG00000039158': 80709,
 'ENSMUSG00000022636': 214,
 'ENSMUSG00000030088': 10840,
 'ENSMUSG00000055471': 238,
 'ENSMUSG00000036777': 54443,
 'ENSMUSG00000031075': 55107,
 'ENSMUSG00000032231': 302,
 'ENSMUSG00000031367': 8905,
 'ENSMUSG00000071847': 147495,
 'ENSMUSG00000037999': 116984,
 'ENSMUSG00000041219': 9824,
 'ENSMUSG00000022799': 57514,
 'ENSMUSG00000030654': 23204,
 'ENSMUSG00000032503': 10777,
 'ENSMUSG00000035277': 170302,
 'ENSMUSG00000031591': 427,
 'ENSMUSG00000020052': 429,
 'ENSMUSG00000033952': 259266,
 'ENSMUSG00000022360': 29028,
 'ENSMUSG00000017550': 79915,
 'ENSMUSG00000025324': 57194,
 'ENSMUSG00000007097': 477,
 'ENSMUSG00000026576': 481,
 'ENSMUSG00000019943': 490,
 'ENSMUSG00000042709': 91647,
 'ENSMUSG00000046876': 6310,
 'ENSMUSG00000060802': 567,
 'ENSMUSG00000033849': 8707,
 'ENSMUSG00000045763': 10409,
 'ENSMUSG00000004892': 63827,
 'ENSMUSG00000048251': 64919,
 'ENSMUSG00000057329': 596,
 'ENSMUSG00000092060': 389206,
 'ENSMUSG00000048186': 222389,
 'ENSMUSG00000017716': 332,
 'ENSMUSG00000034663': 55589,
 'ENSMUSG00000039004': 654,
 'ENSMUSG00000031963': 168667,
 'ENSMUSG00000022687': 91653,
 'ENSMUSG00000017146': 672,
 'ENSMUSG00000041147': 675,
 'ENSMUSG00000004031': 57795,
 'ENSMUSG00000035131': 339479,
 'ENSMUSG00000023175': 682,
 'ENSMUSG00000000202': 388419,
 'ENSMUSG00000036478': 694,
 'ENSMUSG00000020423': 7832,
 'ENSMUSG00000049630': 389941,
 'ENSMUSG00000015968': 776,
 'ENSMUSG00000004110': 777,
 'ENSMUSG00000040118': 781,
 'ENSMUSG00000010066': 9254,
 'ENSMUSG00000019146': 10369,
 'ENSMUSG00000066189': 10368,
 'ENSMUSG00000064115': 253559,
 'ENSMUSG00000028222': 793,
 'ENSMUSG00000029761': None,
 'ENSMUSG00000003814': 811,
 'ENSMUSG00000025468': 50632,
 'ENSMUSG00000053819': 817,
 'ENSMUSG00000046447': 55450,
 'ENSMUSG00000022211': 90668,
 'ENSMUSG00000028977': 54897,
 'ENSMUSG00000006362': 863,
 'ENSMUSG00000024647': 147381,
 'ENSMUSG00000044033': 285025,
 'ENSMUSG00000056531': 343099,
 'ENSMUSG00000022665': 151887,
 'ENSMUSG00000032532': 885,
 'ENSMUSG00000028195': 3491,
 'ENSMUSG00000041431': 891,
 'ENSMUSG00000070348': 595,
 'ENSMUSG00000000184': 894,
 'ENSMUSG00000055447': 961,
 'ENSMUSG00000025351': 967,
 'ENSMUSG00000037706': 975,
 'ENSMUSG00000030342': 928,
 'ENSMUSG00000006398': 991,
 'ENSMUSG00000048922': 157313,
 'ENSMUSG00000023505': 83461,
 'ENSMUSG00000055612': 83879,
 'ENSMUSG00000021175': 55536,
 'ENSMUSG00000028873': 55143,
 'ENSMUSG00000031673': 1009,
 'ENSMUSG00000040452': 1010,
 'ENSMUSG00000031841': 1012,
 'ENSMUSG00000000305': 1002,
 'ENSMUSG00000039385': 1004,
 'ENSMUSG00000025370': 1007,
 'ENSMUSG00000040274': 1021,
 'ENSMUSG00000037664': None,
 'ENSMUSG00000037628': 1033,
 'ENSMUSG00000038119': 50937,
 'ENSMUSG00000002107': 10659,
 'ENSMUSG00000016028': 9620,
 'ENSMUSG00000029177': 1058,
 'ENSMUSG00000045328': 1062,
 'ENSMUSG00000026605': 1063,
 'ENSMUSG00000045273': 64946,
 'ENSMUSG00000071550': 55779,
 'ENSMUSG00000073077': None,
 'ENSMUSG00000040473': 79846,
 'ENSMUSG00000041235': 55636,
 'ENSMUSG00000030077': 10752,
 'ENSMUSG00000022860': 140578,
 'ENSMUSG00000029516': 11113,
 'ENSMUSG00000037725': 26586,
 'ENSMUSG00000048327': 150468,
 'ENSMUSG00000062248': 1164,
 'ENSMUSG00000007041': 1192,
 'ENSMUSG00000042489': 63967,
 'ENSMUSG00000022037': 1191,
 'ENSMUSG00000047419': None,
 'ENSMUSG00000044288': 1268,
 'ENSMUSG00000055022': 1272,
 'ENSMUSG00000033063': 79937,
 'ENSMUSG00000070695': 129684,
 'ENSMUSG00000027966': 1301,
 'ENSMUSG00000032332': 1303,
 'ENSMUSG00000001435': 80781,
 'ENSMUSG00000026141': 1310,
 'ENSMUSG00000079022': 169044,
 'ENSMUSG00000063564': 91522,
 'ENSMUSG00000058897': 84570,
 'ENSMUSG00000022483': 1280,
 'ENSMUSG00000031502': 1282,
 'ENSMUSG00000031503': 1284,
 'ENSMUSG00000031274': 1287,
 'ENSMUSG00000031273': 1288,
 'ENSMUSG00000026042': 1290,
 'ENSMUSG00000036103': 81035,
 'ENSMUSG00000032649': 23127,
 'ENSMUSG00000037852': 1363,
 'ENSMUSG00000062980': 79974,
 'ENSMUSG00000032564': 131034,
 'ENSMUSG00000024900': 1374,
 'ENSMUSG00000035403': 286204,
 'ENSMUSG00000053007': 9586,
 'ENSMUSG00000022723': 131544,
 'ENSMUSG00000030905': 1428,
 'ENSMUSG00000014599': 1435,
 'ENSMUSG00000028804': 114784,
 'ENSMUSG00000022311': 114788,
 'ENSMUSG00000032911': 1464,
 'ENSMUSG00000032482': 10675,
 'ENSMUSG00000027447': 1471,
 'ENSMUSG00000054196': 115908,
 'ENSMUSG00000021939': 1508,
 'ENSMUSG00000030560': 1075,
 'ENSMUSG00000007891': 1509,
 'ENSMUSG00000021477': 1515,
 'ENSMUSG00000042589': 23316,
 'ENSMUSG00000061353': 6387,
 'ENSMUSG00000044365': 80319,
 'ENSMUSG00000027015': 79901,
 'ENSMUSG00000063415': 56603,
 'ENSMUSG00000040260': 23500,
 'ENSMUSG00000022150': 1601,
 'ENSMUSG00000055639': 1602,
 'ENSMUSG00000028159': 27071,
 'ENSMUSG00000026385': 1622,
 'ENSMUSG00000035107': 131566,
 'ENSMUSG00000060534': 1630,
 'ENSMUSG00000022129': 1638,
 'ENSMUSG00000028194': 23576,
 'ENSMUSG00000028175': 55635,
 'ENSMUSG00000036095': 1607,
 'ENSMUSG00000022861': 1608,
 'ENSMUSG00000021707': 1719,
 'ENSMUSG00000022021': 81624,
 'ENSMUSG00000028031': 27123,
 'ENSMUSG00000031523': 10395,
 'ENSMUSG00000003279': 9229,
 'ENSMUSG00000037544': 9787,
 'ENSMUSG00000014773': 28514,
 'ENSMUSG00000003436': 10683,
 'ENSMUSG00000041911': 1745,
 'ENSMUSG00000023391': 1746,
 'ENSMUSG00000029755': 1749,
 'ENSMUSG00000029754': 1750,
 'ENSMUSG00000058325': 1793,
 'ENSMUSG00000025558': 23348,
 'ENSMUSG00000036815': 57628,
 'ENSMUSG00000043067': 23333,
 'ENSMUSG00000059898': 1825,
 'ENSMUSG00000032087': 57453,
 'ENSMUSG00000037474': 51514,
 'ENSMUSG00000018983': 1870,
 'ENSMUSG00000016477': 1871,
 'ENSMUSG00000046179': 79733,
 'ENSMUSG00000057098': 1879,
 'ENSMUSG00000026051': 84417,
 'ENSMUSG00000031616': 1909,
 'ENSMUSG00000022122': 1910,
 'ENSMUSG00000036611': 80820,
 'ENSMUSG00000022441': 64800,
 'ENSMUSG00000063600': None,
 'ENSMUSG00000020122': 1956,
 'ENSMUSG00000038418': 1958,
 'ENSMUSG00000006941': 10289,
 'ENSMUSG00000008489': 1993,
 'ENSMUSG00000048988': 392617,
 'ENSMUSG00000008398': 2004,
 'ENSMUSG00000034164': 129080,
 'ENSMUSG00000022505': 2013,
 'ENSMUSG00000043969': 2018,
 'ENSMUSG00000041773': 8507,
 'ENSMUSG00000022425': 5168,
 'ENSMUSG00000035245': 285203,
 'ENSMUSG00000032446': 8320,
 'ENSMUSG00000024140': 2034,
 'ENSMUSG00000052504': 2042,
 'ENSMUSG00000026235': 2043,
 'ENSMUSG00000029245': 2044,
 'ENSMUSG00000032537': 2047,
 'ENSMUSG00000062209': 2066,
 'ENSMUSG00000001946': 90952,
 'ENSMUSG00000022034': 157570,
 'ENSMUSG00000036617': 56243,
 'ENSMUSG00000032035': 2113,
 'ENSMUSG00000004151': 2115,
 'ENSMUSG00000017724': 2118,
 'ENSMUSG00000039903': 59271,
 'ENSMUSG00000039748': 9156,
 'ENSMUSG00000052397': 7430,
 'ENSMUSG00000028128': 2152,
 'ENSMUSG00000019874': 2173,
 'ENSMUSG00000036800': 51059,
 'ENSMUSG00000041930': 84915,
 'ENSMUSG00000032815': 2175,
 'ENSMUSG00000039187': 55215,
 'ENSMUSG00000070047': 2195,
 'ENSMUSG00000074505': 120114,
 'ENSMUSG00000064080': 2199,
 'ENSMUSG00000024598': 2201,
 'ENSMUSG00000024742': 2237,
 'ENSMUSG00000021743': 55079,
 'ENSMUSG00000034037': 152273,
 'ENSMUSG00000020021': 55785,
 'ENSMUSG00000031565': 2260,
 'ENSMUSG00000054252': 2261,
 'ENSMUSG00000075324': 55137,
 'ENSMUSG00000029781': 11328,
 'ENSMUSG00000047787': 23769,
 'ENSMUSG00000047414': 23768,
 'ENSMUSG00000029648': 2321,
 'ENSMUSG00000040181': 2326,
 'ENSMUSG00000026193': 2335,
 'ENSMUSG00000039286': 64778,
 'ENSMUSG00000021250': 2353,
 'ENSMUSG00000003545': 2354,
 'ENSMUSG00000030067': None,
 'ENSMUSG00000029563': None,
 'ENSMUSG00000021765': 10468,
 'ENSMUSG00000022816': 11167,
 'ENSMUSG00000034098': 56884,
 'ENSMUSG00000000560': 2555,
 'ENSMUSG00000029212': 2560,
 'ENSMUSG00000070880': 2571,
 'ENSMUSG00000026787': 2572,
 'ENSMUSG00000021453': 10912,
 'ENSMUSG00000024064': 79623,
 'ENSMUSG00000047261': 2596,
 'ENSMUSG00000074802': 283431,
 'ENSMUSG00000058624': 9615,
 'ENSMUSG00000051235': 348654,
 'ENSMUSG00000025089': 2674,
 'ENSMUSG00000055737': 2690,
 'ENSMUSG00000029638': 113263,
 'ENSMUSG00000025407': 2735,
 'ENSMUSG00000021318': 2737,
 'ENSMUSG00000036402': 55970,
 'ENSMUSG00000031119': 2239,
 'ENSMUSG00000058571': 10082,
 'ENSMUSG00000046961': 165829,
 'ENSMUSG00000020524': 2890,
 'ENSMUSG00000033981': 2891,
 'ENSMUSG00000001986': 2892,
 'ENSMUSG00000025892': 2893,
 'ENSMUSG00000022935': 2897,
 'ENSMUSG00000056073': 2898,
 'ENSMUSG00000001985': 2899,
 'ENSMUSG00000059003': 2903,
 'ENSMUSG00000030209': 2904,
 'ENSMUSG00000002771': 2906,
 'ENSMUSG00000039579': 116443,
 'ENSMUSG00000003974': 2913,
 'ENSMUSG00000049583': 2915,
 'ENSMUSG00000056755': 2917,
 'ENSMUSG00000034708': 2896,
 'ENSMUSG00000024517': 2922,
 'ENSMUSG00000033910': 2982,
 'ENSMUSG00000022367': 3037,
 'ENSMUSG00000025001': 3070,
 'ENSMUSG00000046240': 220296,
 'ENSMUSG00000021665': 3074,
 'ENSMUSG00000044783': 55355,
 'ENSMUSG00000000628': 3099,
 'ENSMUSG00000003949': 3131,
 'ENSMUSG00000066842': 83872,
 'ENSMUSG00000054717': 3148,
 'ENSMUSG00000003038': None,
 'ENSMUSG00000020330': 3161,
 'ENSMUSG00000059325': 84525,
 'ENSMUSG00000051022': 9957,
 'ENSMUSG00000078591': 9951,
 'ENSMUSG00000062184': 90161,
 'ENSMUSG00000020048': 7184,
 'ENSMUSG00000026864': 3309,
 'ENSMUSG00000050783': 3355,
 'ENSMUSG00000006205': 5654,
 'ENSMUSG00000020644': 3398,
 'ENSMUSG00000021379': 3400,
 'ENSMUSG00000020053': 3479,
 'ENSMUSG00000039323': 3485,
 'ENSMUSG00000020427': 3486,
 'ENSMUSG00000017493': 3487,
 'ENSMUSG00000026185': 3488,
 'ENSMUSG00000036256': 3490,
 'ENSMUSG00000035551': 347252,
 'ENSMUSG00000022790': 152404,
 'ENSMUSG00000025997': 22807,
 'ENSMUSG00000052372': 11141,
 'ENSMUSG00000059203': 26280,
 'ENSMUSG00000040612': 387597,
 'ENSMUSG00000024660': 3619,
 'ENSMUSG00000041324': 3624,
 'ENSMUSG00000048458': 55924,
 'ENSMUSG00000032737': 3636,
 'ENSMUSG00000060798': 27152,
 'ENSMUSG00000021676': 10788,
 'ENSMUSG00000028068': 128239,
 'ENSMUSG00000046192': 154865,
 'ENSMUSG00000042258': 3670,
 'ENSMUSG00000037206': 3671,
 'ENSMUSG00000042284': 3672,
 'ENSMUSG00000027009': 3676,
 'ENSMUSG00000027111': 3655,
 'ENSMUSG00000022817': 3693,
 'ENSMUSG00000025321': 3696,
 'ENSMUSG00000031239': 9452,
 'ENSMUSG00000038855': 3707,
 'ENSMUSG00000027276': 182,
 'ENSMUSG00000053062': 58494,
 'ENSMUSG00000024165': 90861,
 'ENSMUSG00000052837': 3726,
 'ENSMUSG00000055675': 9920,
 'ENSMUSG00000035681': 3747,
 'ENSMUSG00000060882': 3751,
 'ENSMUSG00000044708': 3766,
 'ENSMUSG00000036760': 51305,
 'ENSMUSG00000056258': 3786,
 'ENSMUSG00000058740': 57582,
 'ENSMUSG00000012443': 3832,
 'ENSMUSG00000036768': 56992,
 'ENSMUSG00000024795': 9585,
 'ENSMUSG00000021294': 26153,
 'ENSMUSG00000034311': 24137,
 'ENSMUSG00000005672': 3815,
 'ENSMUSG00000019966': 4254,
 'ENSMUSG00000037465': 7071,
 'ENSMUSG00000029178': 51274,
 'ENSMUSG00000033863': 687,
 'ENSMUSG00000027326': 57082,
 'ENSMUSG00000019846': 3910,
 'ENSMUSG00000002900': 3912,
 'ENSMUSG00000035202': 23395,
 'ENSMUSG00000032193': 3949,
 'ENSMUSG00000027985': 51176,
 'ENSMUSG00000067242': 9211,
 'ENSMUSG00000021190': 5641,
 'ENSMUSG00000020140': 8549,
 'ENSMUSG00000106379': 375612,
 'ENSMUSG00000000247': 9355,
 'ENSMUSG00000029595': 64211,
 'ENSMUSG00000026890': 26468,
 'ENSMUSG00000023022': 51474,
 'ENSMUSG00000053846': 9388,
 'ENSMUSG00000028266': 8543,
 'ENSMUSG00000032334': 4016,
 'ENSMUSG00000038668': 1902,
 'ENSMUSG00000020607': 151354,
 'ENSMUSG00000030029': 26018,
 'ENSMUSG00000049252': 53353,
 'ENSMUSG00000027253': 4038,
 'ENSMUSG00000050587': 57689,
 'ENSMUSG00000019892': 84125,
 'ENSMUSG00000001247': 51599,
 'ENSMUSG00000001870': 4052,
 'ENSMUSG00000024940': 4054,
 'ENSMUSG00000063297': 338645,
 'ENSMUSG00000055435': 4094,
 'ENSMUSG00000031232': 84061,
 'ENSMUSG00000061143': 55534,
 'ENSMUSG00000005142': 4125,
 'ENSMUSG00000052727': 4131,
 'ENSMUSG00000032135': 4162,
 'ENSMUSG00000026669': 55388,
 'ENSMUSG00000034912': 161357,
 'ENSMUSG00000027239': 4192,
 'ENSMUSG00000005583': 4208,
 'ENSMUSG00000024593': 84466,
 'ENSMUSG00000036466': 84465,
 'ENSMUSG00000020160': None,
 'ENSMUSG00000027210': 4212,
 'ENSMUSG00000051855': 4232,
 'ENSMUSG00000060572': 4237,
 'ENSMUSG00000042436': 4239,
 'ENSMUSG00000030605': 4240,
 'ENSMUSG00000018169': 4242,
 'ENSMUSG00000028655': 84879,
 'ENSMUSG00000019888': 25834,
 'ENSMUSG00000047534': 55320,
 'ENSMUSG00000031004': 4288,
 'ENSMUSG00000035805': 23209,
 'ENSMUSG00000000957': 4323,
 'ENSMUSG00000017737': 4318,
 'ENSMUSG00000032221': 55329,
 'ENSMUSG00000073910': 79817,
 'ENSMUSG00000020000': 26002,
 'ENSMUSG00000016386': 744,
 'ENSMUSG00000020695': 9902,
 'ENSMUSG00000069769': 124540,
 'ENSMUSG00000031604': 6307,
 'ENSMUSG00000031207': 4478,
 'ENSMUSG00000025912': 4603,
 'ENSMUSG00000022443': 4627,
 'ENSMUSG00000067818': 10398,
 'ENSMUSG00000022272': 4651,
 'ENSMUSG00000022020': 79612,
 'ENSMUSG00000044968': 222236,
 'ENSMUSG00000022762': 4685,
 'ENSMUSG00000022678': 54820,
 'ENSMUSG00000049001': 79625,
 'ENSMUSG00000027977': 9348,
 'ENSMUSG00000027971': 64579,
 'ENSMUSG00000022055': 4747,
 'ENSMUSG00000040037': 257194,
 'ENSMUSG00000039396': 55247,
 'ENSMUSG00000004891': None,
 'ENSMUSG00000050321': 81832,
 'ENSMUSG00000036902': 81831,
 'ENSMUSG00000029832': 9603,
 'ENSMUSG00000028565': 4774,
 'ENSMUSG00000001911': 4784,
 'ENSMUSG00000000120': 4804,
 'ENSMUSG00000059493': 4810,
 'ENSMUSG00000021806': 22795,
 'ENSMUSG00000021068': 51199,
 'ENSMUSG00000038879': 79815,
 'ENSMUSG00000027574': 128414,
 'ENSMUSG00000063887': 22871,
 'ENSMUSG00000067786': 4826,
 'ENSMUSG00000026923': 4851,
 'ENSMUSG00000027878': 4853,
 'ENSMUSG00000038146': 4854,
 'ENSMUSG00000021047': 4857,
 'ENSMUSG00000001988': 4861,
 'ENSMUSG00000021010': 64067,
 'ENSMUSG00000059991': 4885,
 'ENSMUSG00000029819': 4852,
 'ENSMUSG00000019803': 7101,
 'ENSMUSG00000069171': 7025,
 'ENSMUSG00000030551': 7026,
 'ENSMUSG00000031618': 4306,
 'ENSMUSG00000026826': 4929,
 'ENSMUSG00000020598': 4897,
 'ENSMUSG00000062991': None,
 'ENSMUSG00000053310': None,
 'ENSMUSG00000048490': 8204,
 'ENSMUSG00000034825': 56675,
 'ENSMUSG00000039114': 51299,
 'ENSMUSG00000025810': 8829,
 'ENSMUSG00000025969': 8828,
 'ENSMUSG00000024109': 9378,
 'ENSMUSG00000066392': None,
 'ENSMUSG00000039480': 221294,
 'ENSMUSG00000049107': 4908,
 'ENSMUSG00000059974': 50863,
 'ENSMUSG00000020902': 9423,
 'ENSMUSG00000020019': 59277,
 'ENSMUSG00000059857': 22854,
 'ENSMUSG00000055254': 4915,
 'ENSMUSG00000020029': 11163,
 'ENSMUSG00000026683': 83540,
 'ENSMUSG00000027306': 51203,
 'ENSMUSG00000048148': 284434,
 'ENSMUSG00000046178': 30010,
 'ENSMUSG00000069132': 11249,
 'ENSMUSG00000046719': 11248,
 'ENSMUSG00000021390': 4969,
 'ENSMUSG00000045991': 9480,
 'ENSMUSG00000062257': 4978,
 'ENSMUSG00000021848': 5015,
 'ENSMUSG00000036353': 64805,
 'ENSMUSG00000051048': 283208,
 'ENSMUSG00000028370': 5069,
 'ENSMUSG00000052062': 117583,
 'ENSMUSG00000034981': 25849,
 'ENSMUSG00000027168': 5080,
 'ENSMUSG00000022033': 55872,
 'ENSMUSG00000038718': 5090,
 'ENSMUSG00000042613': 57326,
 'ENSMUSG00000049100': 57575,
 'ENSMUSG00000034755': 27328,
 'ENSMUSG00000052613': 65217,
 'ENSMUSG00000035566': 27253,
 'ENSMUSG00000029108': 5099,
 'ENSMUSG00000055421': 5101,
 'ENSMUSG00000040204': 9768,
 'ENSMUSG00000090223': 5121,
 'ENSMUSG00000027419': 5126,
 'ENSMUSG00000059173': 5136,
 'ENSMUSG00000053965': 8654,
 'ENSMUSG00000029231': 5156,
 'ENSMUSG00000024620': 5159,
 'ENSMUSG00000028583': 10630,
 'ENSMUSG00000036218': 29951,
 'ENSMUSG00000021196': 5214,
 'ENSMUSG00000062866': 9749,
 'ENSMUSG00000053398': 26227,
 'ENSMUSG00000020205': 22822,
 'ENSMUSG00000033149': 90102,
 'ENSMUSG00000023913': 7941,
 'ENSMUSG00000019817': 5325,
 'ENSMUSG00000031538': 5327,
 'ENSMUSG00000024998': 51196,
 'ENSMUSG00000045659': 144100,
 'ENSMUSG00000028517': 8613,
 'ENSMUSG00000044667': 9890,
 'ENSMUSG00000017754': 5360,
 'ENSMUSG00000026640': 5362,
 'ENSMUSG00000029765': 91584,
 'ENSMUSG00000074785': 10154,
 'ENSMUSG00000030123': 23129,
 'ENSMUSG00000018217': 5376,
 'ENSMUSG00000006678': 5422,
 'ENSMUSG00000021668': 51426,
 'ENSMUSG00000032667': 5445,
 'ENSMUSG00000008496': 5452,
 'ENSMUSG00000033871': 133522,
 'ENSMUSG00000016487': 8496,
 'ENSMUSG00000038943': 9055,
 'ENSMUSG00000039410': 63976,
 'ENSMUSG00000025289': 10549,
 'ENSMUSG00000029334': 5593,
 'ENSMUSG00000010175': 5629,
 'ENSMUSG00000032841': 79899,
 'ENSMUSG00000015476': None,
 'ENSMUSG00000026586': 5396,
 'ENSMUSG00000036030': 283659,
 'ENSMUSG00000042256': 442213,
 'ENSMUSG00000026730': 9317,
 'ENSMUSG00000027864': 5738,
 'ENSMUSG00000029838': 5764,
 'ENSMUSG00000020154': 5787,
 'ENSMUSG00000019889': 5796,
 'ENSMUSG00000033278': 5797,
 'ENSMUSG00000020151': 5801,
 'ENSMUSG00000053141': 11122,
 'ENSMUSG00000068748': 5803,
 'ENSMUSG00000027832': 5806,
 'ENSMUSG00000023015': 29127,
 'ENSMUSG00000030346': 10635,
 'ENSMUSG00000078773': 25788,
 'ENSMUSG00000048424': 202151,
 'ENSMUSG00000022469': 10411,
 'ENSMUSG00000038132': 221662,
 'ENSMUSG00000026970': 5937,
 'ENSMUSG00000039607': 27303,
 'ENSMUSG00000005973': 5954,
 'ENSMUSG00000028476': 8434,
 'ENSMUSG00000042453': 5649,
 'ENSMUSG00000029249': 5978,
 'ENSMUSG00000052395': 91869,
 'ENSMUSG00000020037': 5992,
 'ENSMUSG00000022018': 28984,
 'ENSMUSG00000038530': 5999,
 'ENSMUSG00000042671': 85397,
 'ENSMUSG00000017692': 162494,
 'ENSMUSG00000046768': 57381,
 'ENSMUSG00000036006': 9750,
 'ENSMUSG00000066800': 6041,
 'ENSMUSG00000017144': 390,
 'ENSMUSG00000070327': 57674,
 'ENSMUSG00000034177': 54894,
 'ENSMUSG00000052516': 6092,
 'ENSMUSG00000032238': 6095,
 'ENSMUSG00000036192': 6096,
 'ENSMUSG00000029608': 22895,
 'ENSMUSG00000027422': None,
 'ENSMUSG00000019880': 84870,
 'ENSMUSG00000071679': 340595,
 'ENSMUSG00000021087': 6252,
 'ENSMUSG00000006586': 862,
 'ENSMUSG00000015843': 6258,
 'ENSMUSG00000021313': 6262,
 'ENSMUSG00000045092': 1901,
 'ENSMUSG00000067586': 1903,
 'ENSMUSG00000024565': 27164,
 'ENSMUSG00000021838': 23034,
 'ENSMUSG00000060487': 389432,
 'ENSMUSG00000038331': 23314,
 'ENSMUSG00000050711': 7857,
 'ENSMUSG00000044770': 256380,
 'ENSMUSG00000075318': 6326,
 'ENSMUSG00000057182': 6328,
 'ENSMUSG00000031610': 11341,
 'ENSMUSG00000022261': 6383,
 'ENSMUSG00000041592': 54549,
 'ENSMUSG00000028780': 10512,
 'ENSMUSG00000022231': 9037,
 'ENSMUSG00000017707': 10955,
 'ENSMUSG00000026249': 5270,
 'ENSMUSG00000000632': 124925,
 'ENSMUSG00000031548': 6422,
 'ENSMUSG00000020354': 6444,
 'ENSMUSG00000039539': 137868,
 'ENSMUSG00000023940': 151648,
 'ENSMUSG00000026039': 151246,
 'ENSMUSG00000029381': 57619,
 'ENSMUSG00000037902': 140885,
 'ENSMUSG00000059182': 8935,
 'ENSMUSG00000017740': 57468,
 'ENSMUSG00000022899': 6565,
 'ENSMUSG00000041920': 9120,
 'ENSMUSG00000030500': 57084,
 'ENSMUSG00000025094': 6571,
 'ENSMUSG00000005089': 6506,
 'ENSMUSG00000005360': 6507,
 'ENSMUSG00000020142': 6509,
 'ENSMUSG00000028645': 6513,
 'ENSMUSG00000026614': 55532,
 'ENSMUSG00000037771': 140679,
 'ENSMUSG00000022462': 54407,
 'ENSMUSG00000010064': 10991,
 'ENSMUSG00000053897': 64116,
 'ENSMUSG00000060961': 8671,
 'ENSMUSG00000023945': 60482,
 'ENSMUSG00000030310': 6529,
 'ENSMUSG00000030307': 6538,
 'ENSMUSG00000041313': 6541,
 'ENSMUSG00000040010': 8140,
 'ENSMUSG00000054640': 6546,
 'ENSMUSG00000030235': 53919,
 'ENSMUSG00000031558': 9353,
 'ENSMUSG00000036867': 4091,
 'ENSMUSG00000028312': 10592,
 'ENSMUSG00000034349': 10051,
 'ENSMUSG00000021136': 64093,
 'ENSMUSG00000019872': 10924,
 'ENSMUSG00000020439': 6525,
 'ENSMUSG00000047793': 25992,
 'ENSMUSG00000063434': 22986,

In [481]:
humangeneentrid = mouse_to_human_dicts.values()
human_info = mg.querymany(humangeneentrid, scopes='entrezgene', fields='ensembl.gene', species='human')

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
19 input query terms found no hit:	['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'No

In [483]:
human_gene_mapper  = {}
for r in human_info:
    word = r.get('ensembl', {}).get('gene') if isinstance(r.get('ensembl'), dict) else None
    if word is not None:
        human_gene_mapper[r["query"]] = word

In [524]:
human_gene_mapper["7546"]

'ENSG00000043355'

In [465]:
for entry in human_orthologs:
    print(entry)

{'query': 'ENSMUSG00000100303', '_id': 'ENSMUSG00000100303', '_score': 27.564543}
{'query': 'ENSMUSG00000086629', '_id': '69964', '_score': 27.564543}
{'query': 'ENSMUSG00000085582', '_id': '100043232', '_score': 27.564543}
{'query': 'ENSMUSG00000074024', '_id': 'ENSMUSG00000074024', '_score': 27.564543}
{'query': 'ENSMUSG00000097760', '_id': '115487119', '_score': 27.564543}
{'query': 'ENSMUSG00000097375', '_id': 'ENSMUSG00000097375', '_score': 27.564543}
{'query': 'ENSMUSG00000086155', '_id': '77323', '_score': 27.564543}
{'query': 'ENSMUSG00000085982', '_id': '319781', '_score': 27.564543}
{'query': 'ENSMUSG00000097736', '_id': '319626', '_score': 27.564543}
{'query': 'ENSMUSG00000030111', '_id': '232345', '_score': 27.564543, 'homologene': {'genes': [[7955, 562067], [7955, 566238], [7955, 569025], [7955, 793035], [7955, 793100], [7955, 100003785], [7955, 100006782], [7955, 100006895], [7955, 100006947], [7955, 100006972], [7955, 100006993], [7955, 100101650], [7955, 100136837], [7955, 100137103], [8364, 619586], [8364, 100489060], [9031, 418251], [9544, 716834], [9598, 465372], [9606, 2], [9615, 477699], [9913, 513856], [10090, 232345], [10116, 24153]], 'id': 37248}}
{'query': 'ENSMUSG00000098284', '_id': 'ENSMUSG00000098284', '_score': 27.564543}
{'query': 'ENSMUSG00000114531', '_id': '328263', '_score': 27.564543}
{'query': 'ENSMUSG00000056735', '_id': '109202', '_score': 27.564543}
{'query': 'ENSMUSG00000015243', '_id': '11303', '_score': 27.564543, 'homologene': {'genes': [[3702, 818768], [6239, 171782], [7955, 558924], [7955, 100136868], [8364, 100491942], [9031, 373945], [9598, 464630], [9606, 19], [9615, 481651], [9913, 535379], [10090, 11303], [10116, 313210]], 'id': 21130}}
{'query': 'ENSMUSG00000041828', '_id': '217258', '_score': 27.564543, 'homologene': {'genes': [[10090, 217258], [10116, 303638]], 'id': 131160}}
{'query': 'ENSMUSG00000032849', '_id': '239273', '_score': 27.564543, 'homologene': {'genes': [[3702, 820496], [3702, 820497], [3702, 820498], [4530, 4327122], [6239, 180691], [7165, 1277037], [7227, 34148], [7227, 35163], [7227, 35366], [7227, 41387], [7227, 42362], [7227, 47905], [7227, 326161], [7955, 368620], [8364, 100491006], [9031, 418791], [9598, 452625], [9606, 10257], [9615, 485523], [10090, 239273], [10116, 170924]], 'id': 74563}}
{'query': 'ENSMUSG00000030249', '_id': '20928', '_score': 27.564543, 'homologene': {'genes': [[7165, 3292067], [7227, 34350], [7955, 561160], [8364, 101733439], [9031, 418200], [9544, 654489], [9598, 465338], [9606, 10060], [9615, 486638], [9913, 100336551], [10090, 20928], [10116, 25560]], 'id': 56521}}
{'query': 'ENSMUSG00000055782', '_id': '26874', '_score': 27.564543, 'homologene': {'genes': [[7165, 1281041], [7227, 43772], [8364, 101730598], [9031, 417694], [9544, 697556], [9598, 466952], [9606, 225], [9615, 477643], [10090, 26874], [10116, 84356]], 'id': 55873}}
{'query': 'ENSMUSG00000044337', '_id': '12778', '_score': 27.564543, 'homologene': {'genes': [[7955, 561050], [7955, 100000764], [8364, 594993], [9031, 428997], [9544, 694428], [9598, 460122], [9606, 57007], [9615, 403964], [9913, 509585], [10090, 12778], [10116, 84348]], 'id': 22419}}
{'query': 'ENSMUSG00000022893', '_id': '11504', '_score': 27.564543, 'homologene': {'genes': [[7955, 565145], [8364, 100151734], [9031, 418479], [9544, 707778], [9598, 473934], [9606, 9510], [9615, 100686153], [9913, 512171], [10090, 11504], [10116, 79252]], 'id': 21381}}
{'query': 'ENSMUSG00000053399', '_id': '208936', '_score': 27.564543, 'homologene': {'genes': [[7955, 100150128], [8364, 100487298], [9031, 100858277], [9544, 712710], [9598, 737513], [9606, 170692], [9615, 489704], [9913, 518395], [10090, 208936], [10116, 361412]], 'id': 65241}}
{'query': 'ENSMUSG00000053441', '_id': '240322', '_score': 27.564543, 'homologene': {'genes': [[8364, 100494209], [9031, 415600], [9544, 705362], [9598, 462039], [9606, 171019], [9615, 609332], [9913, 537961], [10090, 240322]], 'id': 15860}}
{'query': 'ENSMUSG00000022894', '_id': '23794', '_score': 27.564543, 'homologene': {'genes': [[7955, 565053], [8364, 100488158], [9031, 427971], [9544, 707672], [9598, 473935], [9606, 11096], [9615, 487713], [9913, 286805], [10090, 23794], [10116, 304135]], 'id': 5109}}
{'query': 'ENSMUSG00000046169', '_id': '108154', '_score': 27.564543, 'homologene': {'genes': [[7955, 569099], [8364, 100490362], [9031, 427160], [9544, 696021], [9598, 471529], [9606, 11174], [9615, 478077], [9913, 540722], [10090, 108154], [10116, 361886]], 'id': 82573}}
{'query': 'ENSMUSG00000030022', '_id': '101401', '_score': 27.564543, 'homologene': {'genes': [[6239, 177850], [7955, 100333407], [9031, 416080], [9544, 698341], [9598, 473333], [9606, 56999], [9615, 606847], [9913, 537051], [10090, 101401], [10116, 312566]], 'id': 18821}}
{'query': 'ENSMUSG00000052551', '_id': '94191', '_score': 27.564543, 'homologene': {'genes': [[7955, 558149], [8364, 100496062], [9031, 420461], [9598, 742985], [9606, 105], [9615, 487153], [9913, 524061], [10090, 94191], [10116, 117088]], 'id': 10276}}
{'query': 'ENSMUSG00000020431', '_id': '432530', '_score': 27.564543, 'homologene': {'genes': [[7165, 1272318], [7227, 32406], [7955, 557026], [8364, 100492373], [9031, 420788], [9544, 697230], [9598, 463392], [9606, 107], [9615, 607357], [9913, 281601], [10090, 432530], [10116, 305509]], 'id': 41419}}
{'query': 'ENSMUSG00000024256', '_id': '11516', '_score': 27.564543, 'homologene': {'genes': [[8364, 100125031], [9031, 408251], [9598, 468489], [9606, 116], [9615, 607433], [9913, 615187], [10090, 11516], [10116, 24166]], 'id': 869}}
{'query': 'ENSMUSG00000025475', '_id': '52389', '_score': 27.564543, 'homologene': {'genes': [[7955, 560847], [8364, 101734680], [9606, 84435], [9913, 518385], [10090, 52389], [10116, 309097]], 'id': 18582}}
{'query': 'ENSMUSG00000033569', '_id': '210933', '_score': 27.564543, 'homologene': {'genes': [[7955, 566117], [8364, 100486275], [9031, 421875], [9544, 714608], [9598, 462808], [9606, 577], [9615, 481870], [9913, 100337167], [10090, 210933], [10116, 301309]], 'id': 1289}}
{'query': 'ENSMUSG00000028184', '_id': '99633', '_score': 27.564543, 'homologene': {'genes': [[6239, 174419], [7955, 57987], [8364, 100494313], [9031, 424545], [9544, 708998], [9598, 456974], [9606, 23266], [9615, 490193], [9913, 281278], [10090, 99633], [10116, 171447]], 'id': 22712}}
{'query': 'ENSMUSG00000037605', '_id': '319387', '_score': 27.564543, 'homologene': {'genes': [[7955, 560631], [8364, 100498069], [9031, 422616], [9544, 712601], [9598, 471232], [9606, 23284], [9615, 482166], [9913, 282651], [10090, 319387], [10116, 170641]], 'id': 22878}}
{'query': 'ENSMUSG00000069170', '_id': '110789', '_score': 27.564543, 'homologene': {'genes': [[7955, 415105], [8364, 100485656], [9031, 431566], [9544, 697794], [9598, 461757], [9606, 84059], [9615, 479153], [9913, 537034], [10090, 110789], [10116, 100362255]], 'id': 19815}}
{'query': 'ENSMUSG00000025083', '_id': '226250', '_score': 27.564543, 'homologene': {'genes': [[7955, 567369], [8364, 101734244], [9031, 423908], [9544, 698518], [9598, 450751], [9606, 84632], [9615, 486898], [9913, 615436], [10090, 226250], [10116, 292130]], 'id': 13057}}
{'query': 'ENSMUSG00000019986', '_id': '52906', '_score': 27.564543, 'homologene': {'genes': [[7955, 562701], [8364, 100487301], [9031, 421693], [9544, 706412], [9598, 472132], [9606, 54806], [9615, 476212], [9913, 528398], [10090, 52906], [10116, 308923]], 'id': 9762}}
{'query': 'ENSMUSG00000039546', '_id': '230959', '_score': 27.564543, 'homologene': {'genes': [[7955, 101887016], [8364, 779816], [9031, 770310], [9598, 745076], [9606, 55966], [9615, 607839], [9913, 616582], [10090, 230959], [10116, 687031]], 'id': 10312}}
{'query': 'ENSMUSG00000039158', '_id': '100182', '_score': 27.564543, 'homologene': {'genes': [[9544, 708252], [9598, 464683], [9606, 80709], [9615, 481687], [9913, 539274], [10090, 100182], [10116, 362530]], 'id': 49947}}
{'query': 'ENSMUSG00000022636', '_id': '11658', '_score': 27.564543, 'homologene': {'genes': [[7955, 30194], [7955, 323919], [8364, 780210], [9031, 396092], [9544, 703777], [9598, 460565], [9606, 214], [9615, 478550], [9913, 281614], [10090, 11658], [10116, 79559]], 'id': 1229}}
{'query': 'ENSMUSG00000030088', '_id': '107747', '_score': 27.564543, 'homologene': {'genes': [[6239, 177999], [7955, 100526683], [8364, 496436], [9544, 716977], [9598, 460655], [9606, 10840], [9913, 505677], [10090, 107747], [10116, 64392]], 'id': 122031}}
{'query': 'ENSMUSG00000055471', '_id': '11682', '_score': 27.564543, 'homologene': {'genes': [[7955, 563509], [8364, 100495071], [9031, 421297], [9598, 459127], [9606, 238], [9615, 483021], [9913, 536642], [10090, 11682], [10116, 266802]], 'id': 68387}}
{'query': 'ENSMUSG00000036777', '_id': '68743', '_score': 27.564543, 'homologene': {'genes': [[7955, 562517], [8364, 100491625], [9031, 420738], [9544, 706404], [9598, 463351], [9606, 54443], [9615, 482401], [9913, 518274], [10090, 68743], [10116, 363031]], 'id': 41281}}
{'query': 'ENSMUSG00000031075', '_id': '101772', '_score': 27.564543, 'homologene': {'genes': [[7227, 42340], [7955, 407698], [8364, 100170550], [9031, 423144], [9544, 708723], [9598, 451719], [9606, 55107], [9615, 611698], [9913, 532126], [10090, 101772], [10116, 309135]], 'id': 75079}}
{'query': 'ENSMUSG00000032231', '_id': '12306', '_score': 27.564543, 'homologene': {'genes': [[7955, 325557], [7955, 799806], [8364, 394517], [9031, 396297], [9544, 706240], [9598, 747018], [9606, 302], [9615, 403435], [9913, 282689], [10090, 12306], [10116, 56611]], 'id': 20857}}
{'query': 'ENSMUSG00000031367', '_id': '108012', '_score': 27.564543, 'homologene': {'genes': [[3702, 816245], [3702, 829694], [4530, 4334331], [4896, 2542885], [4932, 850868], [5141, 5847413], [6239, 178989], [7165, 1274441], [7227, 42835], [7955, 327237], [8364, 733931], [9031, 418621], [9544, 713244], [9598, 737479], [9606, 8905], [9615, 611468], [9913, 616331], [10090, 108012], [10116, 302671], [28985, 2895385], [33169, 4621918], [318829, 2679123]], 'id': 2908}}
{'query': 'ENSMUSG00000071847', '_id': '494504', '_score': 27.564543, 'homologene': {'genes': [[7955, 100332639], [8364, 448576], [9031, 426765], [9544, 114673868], [9598, 455287], [9606, 147495], [9615, 480209], [9913, 509040], [10090, 494504], [10116, 689616]], 'id': 77420}}
{'query': 'ENSMUSG00000037999', '_id': '212285', '_score': 27.564543, 'homologene': {'genes': [[7955, 559690], [8364, 100494395], [9031, 428790], [9544, 702115], [9598, 461158], [9606, 116984], [9615, 488840], [9913, 512010], [10090, 212285], [10116, 305367]], 'id': 9064}}
{'query': 'ENSMUSG00000041219', '_id': '228482', '_score': 27.564543, 'homologene': {'genes': [[7955, 406608], [8364, 100158559], [9031, 423289], [9544, 695823], [9598, 453291], [9606, 9824], [9615, 487476], [9913, 617811], [10090, 228482], [10116, 296060]], 'id': 8862}}
{'query': 'ENSMUSG00000022799', '_id': '12549', '_score': 27.564543, 'homologene': {'genes': [[9544, 712145], [9598, 745057], [9606, 57514], [9615, 487992], [9913, 515490], [10090, 12549], [10116, 288093]], 'id': 10644}}
{'query': 'ENSMUSG00000030654', '_id': '54208', '_score': 27.564543, 'homologene': {'genes': [[7227, 42027], [7955, 394087], [8364, 548885], [9031, 416604], [9544, 693296], [9598, 453960], [9606, 23204], [9615, 480791], [9615, 100856583], [10090, 54208], [10116, 293551]], 'id': 41008}}
{'query': 'ENSMUSG00000032503', '_id': '74100', '_score': 27.564543, 'homologene': {'genes': [[9031, 428459], [9544, 707139], [9598, 470786], [9606, 10777], [9615, 477016], [10090, 74100], [10116, 363153]], 'id': 32306}}
{'query': 'ENSMUSG00000035277', '_id': '11878', '_score': 27.564543, 'homologene': {'genes': [[9544, 699892], [9606, 170302], [9615, 608251], [10090, 11878], [10116, 317268]], 'id': 68998}}
{'query': 'ENSMUSG00000031591', '_id': '11886', '_score': 27.564543, 'homologene': {'genes': [[6239, 173120], [7955, 393549], [8364, 100485700], [9031, 422727], [9544, 703699], [9598, 464022], [9606, 427], [9615, 482897], [9913, 510620], [10090, 11886], [10116, 84431]], 'id': 10504}}
{'query': 'ENSMUSG00000020052', '_id': '17172', '_score': 27.564543, 'homologene': {'genes': [[7955, 30466], [8364, 100490701], [9544, 698820], [9598, 452184], [9606, 429], [9615, 482628], [9913, 540473], [10090, 17172], [10116, 64186]], 'id': 31234}}
{'query': 'ENSMUSG00000033952', '_id': '12316', '_score': 27.564543, 'homologene': {'genes': [[7955, 554173], [8364, 100379990], [9031, 424354], [9544, 711153], [9598, 449566], [9606, 259266], [9615, 480009], [9913, 534849], [10090, 12316], [10116, 289054]], 'id': 7650}}
{'query': 'ENSMUSG00000022360', '_id': '70472', '_score': 27.564543, 'homologene': {'genes': [[7955, 335063], [8364, 100496913], [9031, 420346], [9544, 704478], [9598, 464369], [9606, 29028], [9615, 475090], [10090, 70472], [10116, 314993]], 'id': 6044}}
{'query': 'ENSMUSG00000017550', '_id': '237877', '_score': 27.564543, 'homologene': {'genes': [[7955, 560591], [8364, 100485754], [9031, 417408], [9544, 713616], [9598, 454559], [9606, 79915], [9615, 491156], [9913, 513059], [10090, 237877], [10116, 303348]], 'id': 32611}}
{'query': 'ENSMUSG00000025324', '_id': '11982', '_score': 27.564543, 'homologene': {'genes': [[3702, 830375], [4530, 4324268], [4896, 2541560], [4932, 851667], [4932, 856913], [5141, 3880770], [7955, 567172], [8364, 100494528], [9031, 418685], [9544, 711435], [9598, 453268], [9606, 57194], [9615, 488691], [9913, 510723], [10090, 11982], [10116, 365266], [28985, 2892067], [33169, 4623088], [318829, 2682772]], 'id': 56461}}
{'query': 'ENSMUSG00000007097', '_id': '98660', '_score': 27.564543, 'homologene': {'genes': [[7955, 64609], [8364, 100125050], [9031, 396468], [9544, 720191], [9598, 457432], [9606, 477], [9615, 488636], [9913, 515161], [10090, 98660], [10116, 24212], [318829, 2680984], [318829, 12986277]], 'id': 47947}}
{'query': 'ENSMUSG00000026576', '_id': '11931', '_score': 27.564543, 'homologene': {'genes': [[7165, 1278962], [7227, 35408], [7955, 64267], [7955, 64273], [8364, 548592], [9031, 396529], [9544, 700443], [9598, 457497], [9606, 481], [9615, 403966], [9913, 519758], [10090, 11931], [10116, 25650]], 'id': 37509}}
{'query': 'ENSMUSG00000019943', '_id': '67972', '_score': 27.564543, 'homologene': {'genes': [[3702, 818754], [3702, 824900], [4530, 4326507], [4530, 4339199], [4530, 4351449], [7955, 378746], [9031, 374244], [9544, 709102], [9598, 452116], [9606, 490], [9615, 403480], [9913, 282641], [10090, 67972], [10116, 29598]], 'id': 55597}}
{'query': 'ENSMUSG00000042709', '_id': '246782', '_score': 27.564543, 'homologene': {'genes': [[3702, 834066], [4530, 4344085], [4896, 2543406], [4932, 853259], [5141, 3881941], [6239, 191004], [7165, 1279845], [7227, 35399], [7955, 560253], [8364, 394633], [9031, 416511], [9544, 699709], [9598, 454483], [9606, 91647], [9615, 489539], [9913, 513521], [10090, 246782], [10116, 303190], [28985, 2896740], [33169, 4620908], [318829, 2682670]], 'id': 34602}}
{'query': 'ENSMUSG00000046876', '_id': '20238', '_score': 27.564543, 'homologene': {'genes': [[7955, 557340], [8364, 100492711], [9031, 420843], [9598, 747421], [9606, 6310], [9615, 488232], [9913, 616399], [10090, 20238], [10116, 25049]], 'id': 281}}
{'query': 'ENSMUSG00000060802', '_id': '12010', '_score': 27.564543, 'homologene': {'genes': [[7955, 30400], [7955, 791742], [9031, 414830], [9544, 712428], [9598, 450170], [9606, 567], [9615, 100855741], [9913, 280729], [9913, 783680], [10090, 12010], [10116, 24223]], 'id': 2987}}
{'query': 'ENSMUSG00000033849', '_id': '26878', '_score': 27.564543, 'homologene': {'genes': [[3702, 839224], [4530, 4340564], [7955, 404633], [8364, 100487440], [9031, 769122], [9544, 712334], [9598, 469624], [9606, 8707], [9615, 607356], [9913, 539815], [10090, 26878], [10116, 686081]], 'id': 74512}}
{'query': 'ENSMUSG00000084960', '_id': '78849', '_score': 27.564543}
{'query': 'ENSMUSG00000098202', '_id': 'ENSMUSG00000098202', '_score': 27.564543}
{'query': 'ENSMUSG00000045763', '_id': '70350', '_score': 27.564543, 'homologene': {'genes': [[9544, 700114], [9598, 100612672], [9606, 10409], [9615, 612722], [9913, 286842], [10090, 70350], [10116, 100910172]], 'id': 38168}}
{'query': 'ENSMUSG00000004892', '_id': '12032', '_score': 27.564543, 'homologene': {'genes': [[7955, 334113], [8364, 100486298], [9031, 425976], [9544, 718545], [9598, 457401], [9606, 63827], [9615, 612102], [9913, 281019], [10090, 12032], [10116, 25393]], 'id': 7244}}
{'query': 'ENSMUSG00000048251', '_id': '58208', '_score': 27.564543, 'homologene': {'genes': [[7955, 100330974], [8364, 100486647], [9031, 423444], [9544, 705238], [9598, 467548], [9606, 64919], [9615, 612476], [9913, 783269], [10090, 58208], [10116, 314423]], 'id': 10974}}
{'query': 'ENSMUSG00000057329', '_id': '12043', '_score': 27.564543, 'homologene': {'genes': [[8364, 100485267], [9031, 396282], [9598, 738409], [9606, 596], [9615, 403416], [9913, 281020], [10090, 12043], [10116, 24224]], 'id': 527}}
{'query': 'ENSMUSG00000092060', '_id': '666938', '_score': 27.564543, 'homologene': {'genes': [[7955, 566937], [8364, 100145654], [9031, 422777], [9544, 702395], [9598, 471183], [9606, 389206], [9615, 482119], [9913, 614525], [10090, 666938], [10116, 681008]], 'id': 52626}}
{'query': 'ENSMUSG00000048186', '_id': '209645', '_score': 27.564543, 'homologene': {'genes': [[7955, 560711], [8364, 100493451], [9031, 419037], [9544, 720932], [9598, 450314], [9606, 222389], [9615, 102156489], [9913, 504404], [10090, 209645], [10116, 361275]], 'id': 17660}}
{'query': 'ENSMUSG00000017716', '_id': '11799', '_score': 27.564543, 'homologene': {'genes': [[7955, 373110], [8364, 733575], [9031, 374078], [9544, 709565], [9598, 455276], [9606, 332], [9615, 442936], [9913, 414925], [10090, 11799], [10116, 64041]], 'id': 37450}}
{'query': 'ENSMUSG00000034663', '_id': '140780', '_score': 27.564543, 'homologene': {'genes': [[7955, 494101], [8364, 100486326], [9031, 422578], [9598, 471194], [9606, 55589], [9615, 487819], [9913, 505766], [10090, 140780], [10116, 498333]], 'id': 34134}}
{'query': 'ENSMUSG00000039004', '_id': '12161', '_score': 27.564543, 'homologene': {'genes': [[7955, 503761], [8364, 100127176], [9031, 420868], [9544, 695091], [9598, 471851], [9606, 654], [9913, 617566], [10090, 12161], [10116, 25644]], 'id': 1300}}
{'query': 'ENSMUSG00000031963', '_id': '73230', '_score': 27.564543, 'homologene': {'genes': [[7165, 1276836], [7227, 45280], [7955, 338246], [8364, 733449], [9031, 420744], [9544, 708120], [9598, 463344], [9606, 168667], [9615, 475280], [9913, 534101], [10090, 73230], [10116, 300455]], 'id': 12494}}
{'query': 'ENSMUSG00000022687', '_id': '117606', '_score': 27.564543, 'homologene': {'genes': [[7955, 334628], [8364, 780199], [9031, 418361], [9544, 709028], [9598, 460588], [9606, 91653], [9615, 487979], [9913, 512018], [10090, 117606], [10116, 360715]], 'id': 32819}}
{'query': 'ENSMUSG00000017146', '_id': '12189', '_score': 27.564543, 'homologene': {'genes': [[9031, 373983], [9544, 712634], [9598, 449497], [9606, 672], [9615, 403437], [9913, 353120], [10090, 12189], [10116, 497672]], 'id': 5276}}
{'query': 'ENSMUSG00000041147', '_id': '12190', '_score': 27.564543, 'homologene': {'genes': [[9031, 374139], [9544, 721981], [9598, 452526], [9606, 675], [9615, 474180], [9913, 507069], [10090, 12190], [10116, 360254]], 'id': 41}}
{'query': 'ENSMUSG00000004031', '_id': '240843', '_score': 27.564543, 'homologene': {'genes': [[7955, 569746], [9031, 424433], [9544, 709377], [9598, 469596], [9606, 57795], [9615, 490330], [9913, 100335482], [10090, 240843], [10116, 286895]], 'id': 10905}}
{'query': 'ENSMUSG00000035131', '_id': '215378', '_score': 27.564543, 'homologene': {'genes': [[7955, 100001603], [8364, 100491213], [9031, 429077], [9544, 713093], [9598, 469620], [9606, 339479], [9615, 478959], [9913, 531710], [10090, 215378], [10116, 286901]], 'id': 17786}}