In [189]:
## Import necessary libraries
import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import os
from rich.console import Console

con = Console()

In [247]:
# load in the data using scanpy
adata = ad.read_h5ad("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/filtered_ms_adata.h5ad")
mouse_data = ad.read_h5ad("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/runs/mouse_geneformer.h5ad")

In [253]:
mouse_data.X

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]],
      shape=(3365, 512), dtype=float32)

The mouse brain data

In [4]:
con = Console()

In [138]:
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv")
con.print("DataFrame loaded successfully.", style="bold green")

DataFrame loaded successfully.

In [139]:
df.columns

Index(['Unnamed: 0', 'cell_type', '2600014E21Rik', '2810403D21Rik',
       '3110099E03Rik', '4632427E13Rik', '6030442K20Rik', '6720427I07Rik',
       '9430041J12Rik', '9530051G07Rik',
       ...
       'Zfp704', 'Zfp804a', 'Zfp868', 'Zfp874b', 'Zgrf1', 'Zic1', 'Zic2',
       'Zic4', 'Zic5', 'Zwilch'],
      dtype='object', length=867)

In [136]:
df["Unnamed: 0"]

0       AAACAGCCAACCGCCA-1
1       AAACAGCCAAGGTCGA-1
2       AAACAGCCAGGAACAT-1
3       AAACAGCCATATTGAC-1
4       AAACAGCCATGGTTAT-1
               ...
3360    TTTGTGGCATAATCGT-1
3361    TTTGTGGCATTTGCTC-1
3362    TTTGTGTTCAATGACC-1
3363    TTTGTTGGTGGAGCAA-1
3364    TTTGTTGGTTAGAGCC-1
Name: Unnamed: 0, Length: 3365, dtype: object

In [128]:
df.index = df.index.astype(str)
con.print("Index converted to string successfully.", style="bold green")

Index converted to string successfully.

In [130]:
df["Unnamed: 0"]

0       AAACAGCCAACCGCCA-1
1       AAACAGCCAAGGTCGA-1
2       AAACAGCCAGGAACAT-1
3       AAACAGCCATATTGAC-1
4       AAACAGCCATGGTTAT-1
               ...
3360    TTTGTGGCATAATCGT-1
3361    TTTGTGGCATTTGCTC-1
3362    TTTGTGTTCAATGACC-1
3363    TTTGTTGGTGGAGCAA-1
3364    TTTGTTGGTTAGAGCC-1
Name: Unnamed: 0, Length: 3365, dtype: object

In [125]:
# turn the objects into a string 
df["Unnamed: 0"] = df["Unnamed: 0"].astype(str)
df["cell_type"] = df["cell_type"].astype(str)

#Transpose the data 
df = df.T
df.iloc[2:, 0:] = df.iloc[2:, 0:].astype(float)

In [83]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364
Unnamed: 0,AAACAGCCAACCGCCA-1,AAACAGCCAAGGTCGA-1,AAACAGCCAGGAACAT-1,AAACAGCCATATTGAC-1,AAACAGCCATGGTTAT-1,AAACATGCACTTACAG-1,AAACCAACAACTGGGA-1,AAACCGCGTCACCAAA-1,AAACCGCGTGCAATGC-1,AAACCGGCAACTAACT-1,...,TTTGTCTAGAATCTCA-1,TTTGTCTAGTCCTTCA-1,TTTGTCTAGTTGCCTC-1,TTTGTGAAGCTGGAAA-1,TTTGTGGCACTCAACA-1,TTTGTGGCATAATCGT-1,TTTGTGGCATTTGCTC-1,TTTGTGTTCAATGACC-1,TTTGTTGGTGGAGCAA-1,TTTGTTGGTTAGAGCC-1
cell_type,Upper Layer,"RG, Astro, OPC",Deeper Layer,Deeper Layer,Subplate,Upper Layer,"RG, Astro, OPC","RG, Astro, OPC",Upper Layer,Upper Layer,...,Upper Layer,Ependymal cells,Upper Layer,Upper Layer,IPCs,Ependymal cells,Upper Layer,IPCs,Deeper Layer,Upper Layer
2600014E21Rik,0.0,0.0,0.0,0.0,0.0,0.693147,0.693147,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2810403D21Rik,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3110099E03Rik,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [150]:
type(df.iloc[:,0].to_frame())

pandas.core.frame.DataFrame

In [172]:
frame_values = df.iloc[:,1:]
frame_values_values = frame_values.values.astype(np.float32)

In [174]:
adata = ad.AnnData(X=frame_values_values)
adata.obs = df.iloc[:,0].to_frame()
con.print("AnnData object created successfully.", style="bold green")

AnnData object created successfully.

In [188]:
adata

AnnData object with n_obs × n_vars = 3365 × 865
    obs: 'cell_type'

In [159]:
adata.write("mouse_brain.h5ad")

Try again

In [ ]:
# Load your CSV
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv", index_col=0)
df["cell_type"] = df["cell_type"].astype(str)

In [231]:
frame = df.iloc[:, 1:].T.astype(np.float32).T.values
frame

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(3365, 865), dtype=float32)

In [228]:
celltype = df.iloc[:,0].to_frame()
celltype

                          cell_type
AAACAGCCAACCGCCA-1      Upper Layer
AAACAGCCAAGGTCGA-1   RG, Astro, OPC
AAACAGCCAGGAACAT-1     Deeper Layer
AAACAGCCATATTGAC-1     Deeper Layer
AAACAGCCATGGTTAT-1         Subplate
...                             ...
TTTGTGGCATAATCGT-1  Ependymal cells
TTTGTGGCATTTGCTC-1      Upper Layer
TTTGTGTTCAATGACC-1             IPCs
TTTGTTGGTGGAGCAA-1     Deeper Layer
TTTGTTGGTTAGAGCC-1      Upper Layer

[3365 rows x 1 columns]

In [241]:
var_names = df.columns[1:].astype(str)
var_names

Index(['2600014E21Rik', '2810403D21Rik', '3110099E03Rik', '4632427E13Rik',
       '6030442K20Rik', '6720427I07Rik', '9430041J12Rik', '9530051G07Rik',
       '9530059O14Rik', 'A2m',
       ...
       'Zfp704', 'Zfp804a', 'Zfp868', 'Zfp874b', 'Zgrf1', 'Zic1', 'Zic2',
       'Zic4', 'Zic5', 'Zwilch'],
      dtype='object', length=865)

In [239]:
adata = ad.AnnData(X=frame)
adata.obs = celltype
adata.obs_names = df.index.astype(str)
adata.var_names = df.columns[1:].astype(str)

In [243]:
adata.var_names

Index(['2600014E21Rik', '2810403D21Rik', '3110099E03Rik', '4632427E13Rik',
       '6030442K20Rik', '6720427I07Rik', '9430041J12Rik', '9530051G07Rik',
       '9530059O14Rik', 'A2m',
       ...
       'Zfp704', 'Zfp804a', 'Zfp868', 'Zfp874b', 'Zgrf1', 'Zic1', 'Zic2',
       'Zic4', 'Zic5', 'Zwilch'],
      dtype='object', length=865)

In [244]:
output_dir = "/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/"
filename = "mouse_brain.h5ad"
filepath = os.path.join(output_dir, filename)
os.makedirs(output_dir, exist_ok=True)

adata.write_h5ad(filepath)
con.print(f"AnnData object saved to {filepath}", style="bold green")

AnnData object saved to /Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain.h5ad

### Third TRY

In [254]:
df = pd.read_csv("/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain_processed_RNA.csv")  # already loaded in your case

# Set index to cell IDs
df = df.set_index("Unnamed: 0")

In [255]:
obs = df[["cell_type"]]                
X = df.drop(columns=["cell_type"])

In [256]:
adata = ad.AnnData(X=X.values, obs=obs, var=pd.DataFrame(index=X.columns), uns={"source": "mouse_brain_processed_RNA"})

In [257]:
output_dir = "/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/"
filename = "mouse_brain1.h5ad"
filepath = os.path.join(output_dir, filename)
os.makedirs(output_dir, exist_ok=True)

adata.write_h5ad(filepath)
con.print(f"AnnData object saved to {filepath}", style="bold green")

AnnData object saved to
/Users/macbook/Desktop/EECS545/545finalproject/Geneformer_project/Datasets/mouse_brain1.h5ad